### ISSUE TITLE
Windows下无法连接clash

### ISSUE THREAD

**Issue by Arstman** [JohanChane/clashtui#14]
Linux下完全Ok， Windows一直无法启动clash。

```bash
23:35:07 [INFO] clashtui - Start Log, level: INFO
23:35:07 [INFO] clashtui::utils::tui - clash_ua: clash.meta
23:35:09 [WARN] clashtui::utils::tui - Fail to connect to clash. Is it Running?
23:35:13 [WARN] clashtui::utils::tui - 由于目标计算机积极拒绝，无法连接。 (os error 10061)
23:35:13 [INFO] clashtui - App init finished
23:35:15 [INFO] clashtui - App Exit
23:35:24 [INFO] clashtui - Start Log, level: INFO
23:35:24 [INFO] clashtui::utils::tui - clash_ua: clash.meta
23:35:26 [WARN] clashtui::utils::tui - Fail to connect to clash. Is it Running?
23:35:30 [WARN] clashtui::utils::tui - 由于目标计算机积极拒绝，无法连接。 (os error 10061)
23:35:30 [INFO] clashtui - App init finished
23:35:31 [INFO] clashtui - App Exit
23:36:15 [INFO] clashtui - Start Log, level: INFO
23:36:15 [INFO] clashtui::utils::tui - clash_ua: clash.meta
23:36:17 [WARN] clashtui::utils::tui - Fail to connect to clash. Is it Running?
23:36:22 [WARN] clashtui::utils::tui - 由于目标计算机积极拒绝，无法连接。 (os error 10061)
23:36:22 [INFO] clashtui - App init finished
23:36:25 [INFO] clashtui - App Exit

```
基本都是这个报错。

但是如果直接使用mihomo按照配置， 是可以正常启动的：

```bash
C:\Users\rooti\scoop\shims\mihomo.exe -d C:\Users\rooti\mihomo -f C:\Users\rooti\mihomo\config.yaml
```

PS: clashtui 的config.yaml 配置如下：
```bash
clash_cfg_dir: C:/Users/rooti/mihomo
clash_core_path: C:/Users/rooti/scoop/shims/mihomo.exe
clash_cfg_path: C:/Users/rooti/mihomo/config.yaml
clash_srv_name: mihomo
is_user: false
edit_cmd: ''
open_dir_cmd: ''
current_profile: ''
```
不太清楚是哪里有问题

**Comment by JohanChane** [comment]
mihomo 服务启动吗? 或者先回车选择一个可用的 profile 试试。

**Comment by Arstman** [comment]
不是， 就是配置完， 再启动clashtui就报错。 

刚刚尝试另外单独启动mihomo， 然后再启动clashtui， 依然是一样的报错

`Fail to connect to clash. Is it Running?`

> mihomo 服务启动吗? 或者先回车选择一个可用的 profile 试试。 使用 `netstat -ano | find "<port>"` 查看端口是否已经启用了。

**Comment by Arstman** [comment]
不是， 就是配置完， 再启动clashtui就报错。 

刚刚尝试另外单独启动mihomo， 然后再启动clashtui， 依然是一样的报错

`Fail to connect to clash. Is it Running?`

> mihomo 服务启动吗? 或者先回车选择一个可用的 profile 试试。 使用 `netstat -ano | find "<port>"` 查看端口是否已经启用了。

**Comment by JohanChane** [comment]
你用这个命令启动 `C:\Users\rooti\scoop\shims\mihomo.exe -d C:\Users\rooti\mihomo -f C:\Users\rooti\mihomo\config.yaml`。使用 netstat -ano | find "<port>" 查看端口是否已经启用了。然后启动 clashtui 看能不能连上。

**Comment by JohanChane** [comment]
如果 external-controller 端口已经启用了,  如果还连不上, 可能是 external-controller 对不上, 将 mihomo 的 config.yaml 的 external-controller 的端口改为 7890。如果原来已经是 7890, 则需要进一步排查原因了。

**Comment by Arstman** [comment]
排查了一圈， 单独mihomo启动都没问题，甚至clashtui启动虽然报错，但是可以正常update profile， 并且能merge， 其它安装服务、切换模式和代理都是正常的。

最后发现问题应该出在 external-controller上， 我这里mihomo启动后监听地址是ipv6格式了：
```bash
time="2024-03-31T01:49:13.514388+08:00" level=info msg="RESTful API listening at: [::]:9090"
``` 

问题是basic config和merge后的clash config文件都是ipv6：false。 

还得查查原因


> 你用这个命令启动 `C:\Users\rooti\scoop\shims\mihomo.exe -d C:\Users\rooti\mihomo -f C:\Users\rooti\mihomo\config.yaml`。使用 `netstat -ano | find "<port>"` 查看端口是否已经启用了。然后启动 clashtui 看能不能连上。

**Comment by Arstman** [comment]
搞定了， 必须将external-control的ip设置为127.0.0.1, 我之前是0.0.0.0

**Comment by JohanChane** [comment]
> 搞定了， 必须将external-control的ip设置为127.0.0.1, 我之前是0.0.0.0

这个是 clashtui 没有考虑到的问题, 之后的版本会改进。

**Comment by JohanChane** [comment]
修复之后的 [clashtui](https://github.com/JohanChane/clashtui/actions/runs/8507629322):
- 如果是 0.0.0.0 则改用 127.0.0.1 作为 controller_api 的 ip。
- 同时 log 可以查看解析之后的 controller_api。

**Comment by JohanChane** [comment]
修复之后的 clashtui:
- 如果是 0.0.0.0 则改用 127.0.0.1 作为 controller_api 的 ip。
- 同时 log 可以查看解析之后的 controller_api。

链接:
- [clashtui-linux-amd64](https://github.com/JohanChane/clashtui/actions/runs/8507629322)
- [clashtui-windows-amd64](https://github.com/JohanChane/clashtui/actions/runs/8508062423)
