### ISSUE TITLE
still tries to update profile with proxy after stopped mihomo service

### ISSUE THREAD

**Issue by ogios** [JohanChane/clashtui#20]
## screenshot
![image](https://github.com/JohanChane/clashtui/assets/96933655/82471afa-8076-41f6-ae31-a7aaef920679)
![image](https://github.com/JohanChane/clashtui/assets/96933655/6933bbad-6602-4427-a07e-5d96acc49630)

## version
```
 ▦ app/clashtui 14:29
◉ ./clashtui --version
0.2.1
```

## update with wget myself (success)
```
 ▦ clashtui/profile_cache ▶  14:22
◇┈⊘ wget "http://*****/***/************?clash=1&extend=1" -O test.yaml
--2024-04-24 14:22:38--  http://*****/***/************?clash=1&extend=1
Resolving ***** (*****)... *.*.*.*
Connecting to ***** (*****)|*.*.*.*|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://*****/***/************?clash=1&extend=1 [following]
--2024-04-24 14:22:40--  http://*****/***/************?clash=1&extend=1
Resolving ***** (*****)... *.*.*.*
Connecting to ***** (*****)|*.*.*.*|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 680351 (664K) [application/octet-stream]
Saving to: ‘test.yaml’

test.yaml                              100%[==========================================================================>] 664.41K  3.12MB/s    in 0.2s    

2024-04-24 14:22:40 (3.12 MB/s) - ‘test.yaml’ saved [680351/680351]

[1]+  Done                    wget http://*****/***/************?clash=1&extend=1
```

**Comment by JohanChane** [comment]
try:
-   [Linux](https://github.com/JohanChane/clashtui/actions/runs/8813276462)
-   [Win](https://github.com/JohanChane/clashtui/actions/runs/8813371157)

**Comment by ogios** [comment]
@JohanChane Linux ok, but one more thing, i have to restart clashtui after stopped mihomo service, the status isn't updated:
![image](https://github.com/JohanChane/clashtui/assets/96933655/565eff20-1af3-4088-a7ad-d68ac60a1500)
![image](https://github.com/JohanChane/clashtui/assets/96933655/425a3439-5fef-4b12-98f7-19f446c39ceb)

**Comment by JohanChane** [comment]
Thank you for your feedback. I will refine it when I have time later.
