### ISSUE TITLE
Selecting profile failed

### ISSUE THREAD

**Issue by BrandonStudio** [JohanChane/clashtui#25]
the timeout of the request was reached

**Comment by JohanChane** [comment]
1. Check if the `mihomo` is running.
2. Check if the `external-controller` is listening.

**Comment by JohanChane** [comment]
Check the log what clashtui detected as your `external-controller`.

**Comment by JohanChane** [comment]
> ```
> 09:54:48 [INFO] clashtui - Start Log, level: INFO
> 09:54:48 [INFO] clashtui::utils::tui - controller_api: http://127.0.0.1:9090
> 09:54:48 [INFO] clashtui::utils::tui - proxy_addr: http://127.0.0.1:7890
> 09:54:48 [INFO] clashtui::utils::tui - clash_ua: Clash
> 09:54:48 [INFO] clashtui - App init finished
> 09:54:59 [ERROR] clashtui::utils::tui::impl_profile - Failed to Patch Profile `GAFN-4`: the timeout of the request was reached
> ```

It's possible that there's an issue with your `GAFN-4` profile. Select the profile and use mihomo api manually. 

```sh
curl "http://127.0.0.1:9090/configs?force=true" -X PUT -d '{"path": "/srv/mihomo/config.yaml", "payload": ""}'
```

**Comment by JohanChane** [comment]
What is the content of your clashtui config.yaml?

**Comment by JohanChane** [comment]
I can't reproduce the bug. You can try [the latest version](https://github.com/JohanChane/clashtui/actions/runs/8981166814).

**Comment by JohanChane** [comment]
How about the other profiles?

**Comment by Jackhr-arch** [comment]
Please try download [this](https://productionresultssa12.blob.core.windows.net/actions-results/8cdbb905-17ee-442d-b2f3-2239173f61a6/workflow-job-run-d5c11ce9-a08a-5bde-783f-1bfee628ff52/artifacts/e5671801dc1791f6afeb1b3ff1233dd9034da28d3ff87e5c07ae1ffdf8ff42ea.zip?rscd=attachment%3B+filename%3D%22Linux_Build.zip%22&se=2024-05-09T08%3A37%3A09Z&sig=OeRKIUIyEXRvW9AqP9Ig07aKJp7FNd%2BVwFSEM2dNtGs%3D&sp=r&spr=https&sr=b&st=2024-05-09T08%3A27%3A04Z&sv=2021-12-02) and use `clashtui.debug`, reproduce the bug and upload the log file content along with mihomo service log

**Comment by JohanChane** [comment]
> Please try download [this](https://productionresultssa12.blob.core.windows.net/actions-results/8cdbb905-17ee-442d-b2f3-2239173f61a6/workflow-job-run-d5c11ce9-a08a-5bde-783f-1bfee628ff52/artifacts/e5671801dc1791f6afeb1b3ff1233dd9034da28d3ff87e5c07ae1ffdf8ff42ea.zip?rscd=attachment%3B+filename%3D%22Linux_Build.zip%22&se=2024-05-09T08%3A37%3A09Z&sig=OeRKIUIyEXRvW9AqP9Ig07aKJp7FNd%2BVwFSEM2dNtGs%3D&sp=r&spr=https&sr=b&st=2024-05-09T08%3A27%3A04Z&sv=2021-12-02) and use `clashtui.debug`, reproduce the bug and upload the log file content along with mihomo service log

I think it's necessary to keep the debug version.

**Comment by Jackhr-arch** [comment]
> > Please try download [this](https://productionresultssa12.blob.core.windows.net/actions-results/8cdbb905-17ee-442d-b2f3-2239173f61a6/workflow-job-run-d5c11ce9-a08a-5bde-783f-1bfee628ff52/artifacts/e5671801dc1791f6afeb1b3ff1233dd9034da28d3ff87e5c07ae1ffdf8ff42ea.zip?rscd=attachment%3B+filename%3D%22Linux_Build.zip%22&se=2024-05-09T08%3A37%3A09Z&sig=OeRKIUIyEXRvW9AqP9Ig07aKJp7FNd%2BVwFSEM2dNtGs%3D&sp=r&spr=https&sr=b&st=2024-05-09T08%3A27%3A04Z&sv=2021-12-02) and use `clashtui.debug`, reproduce the bug and upload the log file content along with mihomo service log
> 
> ```
> <Error>
> <Code>AuthenticationFailed</Code>
> <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:cbb5b469-101e-0006-24ec-a190b2000000 Time:2024-05-09T08:39:46.8841070Z</Message>
> <AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Thu, 09 May 2024 08:27:04 GMT] - Expiry [Thu, 09 May 2024 08:37:09 GMT] - Current [Thu, 09 May 2024 08:39:46 GMT]</AuthenticationErrorDetail>
> </Error>
> ```

my fault, should be [this](https://github.com/Jackhr-arch/clashtui/actions/runs/9014545687/artifacts/1487059648)

**Comment by JohanChane** [comment]
> Another error is "unexpected end of file" when updating profile. The same URL works well on Clash Verge and Clash for Windows and cURL

The issue may be related to the network quality or timeout. The development version of clashtui has added a `timeout` option. Set the `timeout` to 0 and test it. If the problem persists, select a usable node for testing and check the mihomo logs for updates on the subscription link. 
https://github.com/JohanChane/clashtui/actions/runs/9089877447

**Comment by JohanChane** [comment]
> BTW, I notice that in the previous updated profile (in `profile_cache`), every line ends with `^M`, which should be `CR`. I don't know whether this makes difference. But just as I have mentioned above, Update and selection were successful just few weeks ago with same profile.

The downloaded profiles are all in `unix` file format in my `Windows` and `Linux` system. I can't reproduce the bug.

**Comment by JohanChane** [comment]
> I think maybe the issue is related to the template. It succeeds now.
> 
> What did I do:
> 
> 1. I switched template from `generic_tpl.yaml` to `generic_tpl_with_all`, resulting in stuck and exceptional exit of the program.
> 2. I exited console (because console echo had been broken due to the exceptional exit) and reran clashtui
> 3. I pressed `u` to update and succeeded, I then pressed `a` to update all and also succeeded.
> 4. I selected the updated profile, also succeeded. But proxy mode is changed to `Rule`
> 
> After these, I tried to switch the mode to `Global`, but nothing changed. I reselected the profile, with mode still `Rule`.



> It seems that timeout problem is also due to template.
> 
> I don't actually need template, but I cannot select an empty one (timeout). What can I do?

Proxy Mode:
-   `ClashSrvCtl->SwitchMode`: This only temporarily changes the mode, not an option. The use case is to modify the mode for convenience in doing certain tasks, such as updating profiles using direct connection mode. If you want to permanently change the mode, please modify it in `basic_clash_config.yaml`. See [ref](https://wiki.metacubex.one/en/config/general/#operation-mode).

Template:
-   If there is no difference between the `rules` in `generic_tpl.yaml` and `generic_tpl_with_all`, it is unlikely that this is the cause of the issue. It is more likely a problem with node selection. You can wait for the nodes to complete url-testing and then update the profiles. For specific reasons, you can check the logs in mihomo.
-   You can choose not to use the template. `clashtui` supports directly importing the subscription link and yaml file. `Templates` are only used to generate yaml files.

Timeout:
-   Update the profile and select it.

**Comment by JohanChane** [comment]
@Jackhr-arch When `timeout=3`, I tested using the template `generic_tpl_with_ruleset.yaml` and found that a timeout error would occur. This issue is likely caused by loading a large number of files. To avoid this issue, I changed the `timeout` to 10 seconds. See [timeout](https://github.com/JohanChane/clashtui/blob/dev/clashtui/api/src/clash.rs#L2).

@BrandonStudio Try https://github.com/JohanChane/clashtui/actions/runs/9160344691. If the timeout issue still occurs, more relevant information will need to be provided.

**Comment by JohanChane** [comment]
> 另外是否考虑将 template 改为像 clash-verge-rev 那样的 patch？

我不清楚 patch 是什么功能, 你有什么应用场景吗?

**Comment by JohanChane** [comment]
> 我知道问题是什么了
> 
> 逻辑是，更新 Profile 的时候，会使用 mihomo 的代理去更新，但是在更新的当下，代理已经过期（不可用），所以更新和选择会报错。
> 
> Workaround 是把 mihomo 的代理模式改成直连后再更新。
> 
> 本 issue 与 template 无关
> 
> 能不能给一个选项，允许选择通过代理更新还是直连更新（保持ua设置）？

可以修改 mihomo mode 为 direct 再更新, 或者添加规则 `- IN-TYPE,INNER,DIRECT`。这两种方案都不方便。后续版本会改进。

**Comment by JohanChane** [comment]
> > 我不清楚 patch 是什么功能, 你有什么应用场景吗?
> 
> https://clash-verge-rev.github.io/guide/merge.html 就是对任何选中的 Profile 打补丁（rules, proxies, proxy groups 等配置），也可以对其它配置进行覆盖，如 ipv6, tun 等

mihomo 使用的配置是 config.yaml, 它是由 `basic_clash_config.yaml` 和当前的 `profile` 合并而成。配合你自己写的模板, 可以完全掌控 `config.yaml` 的所有内容(除了 proxies 字段)。如果这不能解决问题, 你是想保留机场的配置, 而是在配置上做一些修改? 或者不想要 `proxy-providers` ?或者是想批处理机场的 `proxies` ? 

如果使用 patch 只修改 rules, 是比较麻烦的, 要手动修改规则使用的 `proxy-groups`, 不如模板方便。

所以你的需求场景是怎样的, 模板功能无法满足?
