### ISSUE TITLE
About privilege escalation

### ISSUE THREAD

**Issue by Jackhr-arch** [JohanChane/clashtui#28]
Currently, the mainline code relies on restarting the program with su privileges to achieve privilege escalation. However, in my opinion, it is best for a program to only elevate privileges when necessary, and it seems that the only operation in the program that requires privilege escalation is when writing to the mihomo configuration file.

Therefore, I think that considering writing the content to a temporary file first, and then using `pkexec mv tmpfile target_config.yaml` after a direct write to the configuration file fails, may be a better approach.

I have currently refactored [a portion of the code](https://github.com/Jackhr-arch/clashtui/blob/b8e842e04e939bb03544159aeef9e02058d0c7d2/clashtui/backend/src/utils/backend/impl_profile.rs#L344) as an example

**Comment by JohanChane** [comment]
Yes, I have also considered this issue. My current approach is just for convenience, but it's not the best. If it's not a multi-user situation, we don't even need to worry about permission issues. We can run `mihomo` as the user itself rather than using the `mihomo` user and group. See [mihomo.service](https://github.com/MetaCubeX/mihomo/blob/Meta/.github/mihomo.service), no `User=mihomo Group=mihomo`

**Comment by Jackhr-arch** [comment]
yeah, that's what I'm using mihomo. [example](https://github.com/Jackhr-arch/clashtui/blob/de5e14668dace0c471f60bbc65961d2d4796407c/README.md#set-up-systemd-user-service)

So how is this idea? If accepted I'll work on it

**Comment by JohanChane** [comment]
I just tried 'no User Group in service unit' and found it not ideal. It's better to set User Group. So let's go with your solution.

**Comment by JohanChane** [comment]
If you think it's feasible, you can proceed without asking for my opinion. If I find something wrong, I will discuss it with you to see if any modifications are needed. This way, it will be more efficient.

**Comment by Jackhr-arch** [comment]
About the source code 

I prefer to write two versions of the code together for version control and error checking. 

Considering the significant deviation between aio and the main branch, I will consider porting the old code to the aio branch, `abandoning the original three branches`, renaming aio to dev, and regenerating the main branch. 

My expectation is that the dev branch will resolve bugs and generate features, and once stable, merge into main and generate a release from main. 

I don’t know what your opinion is, but if you disagree, I will consider submitting code to dev and ultimately abandoning the aio bran

**Comment by JohanChane** [comment]
I agree, you go ahead and do it.

**Comment by JohanChane** [comment]
Subsequent releases should also include a development version to engage more people in testing.
