### ISSUE TITLE
还是开发类似v2rayA的基于WEB管理clash的UI作品较好

### ISSUE THREAD

**Issue by DanielZWX** [JohanChane/clashtui#3]

**Comment by JohanChane** [comment]
不是有 [clash-verge](https://github.com/zzzgydi/clash-verge) 吗? 我觉得没有必要重复造轮子。我是比较喜欢 tui。clashtui 配合 metacubexd 我觉得已经够用了。

**Comment by pengdaCN** [comment]
可以在wsl中用吗，这个

**Comment by JohanChane** [comment]
> 可以在wsl中用吗，这个

不是支持 window 平台吗
