### ISSUE TITLE
[Feat]: terminate connection in clashtui

### ISSUE THREAD

**Issue by Jackhr-arch** [JohanChane/clashtui#34]
### Please make sure you have read the above considerations and tick the confirmation box below.

- [X] I'm sure this is a feature that has never been proposed and implemented.
- [X] I've looked for the question I'm asking in [Issue Tracker](https://github.com/JohanChane/clashtui/issues?q=is%3Aissue), and I didn't find the ISSUE for the same question.

### Describe the solution

Search, find and terminate connection in clashtui terminal user interface 

Related to #33

**Comment by Jackhr-arch** [comment]
Do you have any suggestions on creating a timer, or we just manually refresh the connection infos? @JohanChane

**Comment by JohanChane** [comment]
> Do you have any suggestions on creating a timer, or we just manually refresh the connection infos? @JohanChane

I think using a timer would be better. I have no recommendations for the timer.

**Comment by Jackhr-arch** [comment]
This tab is basically ok. 
I use `ratatui::widgets::Table` to display basic infos, `r` to refresh infos.
One press `Enter` on one item turns on the extra infos dialog (Not yet done), with another `Enter` to terminate this connection.
>NOTE: Currently, user have to do manually refresh. 
NOTE: This table has no style now, you can do some design. 

About `search` function, I'm not gonna to do it now.

About other things.
 - Now terminal should be able to recover to normal even after panic.
 - Gonna to replace `MsgPopup` with `ConfirmPopup` to reduce some data usage.
 - Current `get_connections` in `impl_conn.rs` return a fixed vector, don't get confused by this. 

About the timer and #36 , I won't do it before other things are done
