### ISSUE TITLE
[wanted help]clash配置该怎么解决route loop的问题

### ISSUE THREAD

**Issue by acking-you** [JohanChane/clashtui#4]
有个场景困扰我很久，一直不知道如何解决😭

我本地已经存在一个 socks5 的代理，比如暴露在 127.0.0.1:1080 。
我是想借助 clash 的 tun mode 截获所有流量并让他们走本地的 socks5 的代理。
直接跑默认配置的话，会发生 loop 死循环，请问该如何在配置中让本地的 1080 端口的服务出口流量不被tun设备代理呢？

**Comment by JohanChane** [comment]
用这个 [basic_clash_config.yaml](https://github.com/JohanChane/clashtui/blob/main/App/basic_clash_config.yaml) 配置是吗?

**Comment by ACking-you** [comment]
> 用这个 [basic_clash_config.yaml](https://github.com/JohanChane/clashtui/blob/main/App/basic_clash_config.yaml) 配置是吗?

是的改了一下，用的本地socks5的proxy服务

**Comment by JohanChane** [comment]
我不了解, 我帮你问了别人。可以用这个试试: PROCESS-NAME,socks-proxy-process-name,DIRECT
clashtui 不解决这类问题的。mihomo 配置是用户掌管的。
