### ISSUE TITLE
［过时依赖］encoding

### ISSUE THREAD

**Issue by Jackhr-arch** [JohanChane/clashtui#40]
根据[这个issue](https://github.com/lifthrasiir/rust-encoding/issues/127)，`encoding`长时间处于无人维护状态，可能存在潜藏的安全漏洞，建议考虑迁移到其他类似的库，如`encoding_rs`等

**Comment by Jackhr-arch** [comment]
> 是的, 可以的。

完成了。

我希望你能测试master分支产物的功能，注意ipc相关的功能。

此外，我建议你在wiki中详尽描述 模板 这一功能，制定处理规则，包括 `proxy-provider` 的保留与否等等。

项目文档严重滞后，且内容分布混乱。建议README仅作简介与索引，使用超链接链接到Doc下的具体内容

其他分支我不再维护，我将master作为主分支维护，建议主仓库也迁移到master

接下来我可能更专注于创建注释，以便你（与可能的其他维护者）理解，所以 #35 #36 不会合并到下一个版本

目前clashtui的设置、数据等储存格式仅是权宜之计，可能需要继续修改，期待你的建议

**Comment by JohanChane** [comment]
> > 是的, 可以的。
> 
> 完成了。
> 
> 我希望你能测试master分支产物的功能，注意ipc相关的功能。
> 
> 此外，我建议你在wiki中详尽描述 模板 这一功能，制定处理规则，包括 `proxy-provider` 的保留与否等等。
> 
> 项目文档严重滞后，且内容分布混乱。建议README仅作简介与索引，使用超链接链接到Doc下的具体内容
> 
> 其他分支我不再维护，我将master作为主分支维护，建议主仓库也迁移到master
> 
> 接下来我可能更专注于创建注释，以便你（与可能的其他维护者）理解，所以 #35 #36 不会合并到下一个版本
> 
> 目前clashtui的设置、数据等储存格式仅是权宜之计，可能需要继续修改，期待你的建议

有空我再搞了。我到时可能会用 Qt 的对象树的概念实现 tui 的对象管理和事件传递。对象树对 ui 编程还是挺方便的。
