### ISSUE TITLE
[Feature Request] ARM64 Support

### ISSUE THREAD

**Issue by BrandonStudio** [JohanChane/clashtui#7]
Support ARM64 (aarch64) for Linux.

**Comment by JohanChane** [comment]
我没有 arm64 的机器, 只是用 rust 的交叉编译编译了 linux-arm64 的版本。你试试能不能用。

https://github.com/JohanChane/clashtui/releases/tag/v0.1.0

**Comment by JohanChane** [comment]
改用 zigbuild 了, 指定 glibc 的版本为 2.17, 你下载来试试。
[clashtui-linux-arm64.tar.gz](https://github.com/JohanChane/clashtui/files/14615392/clashtui-linux-arm64.tar.gz)
